---
definitions:
  Acknowledge:
    type: object
    properties:
      message:
        type: string
        example: Success
  VSIStatus:
    type: object
    properties:
      status_id:
        type: string
        example: 1
      vsiId:
        type: string
        example: 1
      status:
        type: string
        example: creating
      statusMessage:
        type: string
        example: Creating Vertical Service Instance
      timestamp:
        type: string
        format: date-time
      
  VS:
    type: object
    required:
      - name
      - vsdId
      - vsiId
      - description
    properties:
      vsiId:
        type: string
        example: 1
      vsdId:
        type: string
        example: 1
      # tenantId:
      #   type: string
      #   example: 1
      name:
        type: string
        example: vetService
      description:
        type: string
        example: desc
      domainId:
        type: string
        example: 1
      mappedInstanceId:
        type: string
        example: 1
      status:
        type: string
        example: online
      userData:
        type: object
        properties:
          dynamicKey:
            type: string
            example: dynamicValue
      domainPlacements:
        type: array
        items:
          type: object
          properties:
            domainId:
              type: string
              example: ITAV
            componentName:
              type: string
              example: test_VSI-3_1
      locationConstraints:
        type: object
        properties:
          lat:
            type: number
            example: 1.1
          long:
            type: number
            example: 1.1
          alt:
            type: number
            example: 1.1
          range:
            type: number
            example: 1.1
      ranEndPointId:
        type: string
        example: 1
      networkSliceId:
        type: string
        example: 1
      nssis:
        type: object
        properties:
          nssiId:
            type: string
            example: 1
          nsstId:
            type: string
            example: 1
          nsDeploymentFlavorId:
            type: string
            example: 1
          nsInstantiationLevelId:
            type: string
            example: 1
          domainId:
            type: string
            example: 1
          status:
            type: string
            example: SUCCESS
      vssis:
        type: object
        properties:
          domainId:
            type: string
            example: 1
          blueprintId:
            type: string
            example: 1
          descriptorId:
            type: string
            example: 1
          instanceId:
            type: string
            example: 1
          verticalServiceStatus:
            type: string
            example: SUCCESS
      nestedVsi:
        type: array
        items:
          type: string
          example: 1
      errorMessage:
        type: string
        example: error
      additionalConf:
        type: array
        items:
          type: object
          properties:
            conf:
              type: string
              example: yaml
            componentName:
              type: string
              example: 3_1-test
info:
  title: VS LCM API
  swagger_ui: True
openapi: 3.0.3