vld:
- name: mgmtnet
  vim-network-name: proj_net
- name: datanet
  vim-network-name: vl_mgmt
additionalParamsForVnf:
- member-vnf-index: "1"
  additionalParams:
    tunnel_address: "10.0.0.1/24"
    tunnel_id: "test"
    vsi_id: "10"
    bandwidth: "30"