netslice-subnet:
- id: interdomain-tunnel-peer
  additionalParamsForVnf:
  - member-vnf-index: "1"
    additionalParams:
      tunnel_address: "10.0.0.1/24"
      tunnel_id: "1"
      vsi_id: "10"
- id: interdomain-ns_2
  additionalParamsForVnf:
  - member-vnf-index: "1"
    additionalParams:
      tunnel_address: "10.0.0.2/24"
      tunnel_id: "2"
      vsi_id: "10"